### ISSUE TITLE
http://httpredir.debian.org/debian Not Found

### ISSUE THREAD

**Issue by imran-uk** [rgeissert/http-redirector#60]
As topic, please fix :)

**Comment by leggewie** [comment]
works for me

**Comment by imran-uk** [comment]
I tried using Google DNS and OpenDNS - I get 404

I tried using http://404checker.com/404-checker, I get 404

I tried from my hosted server using "links" - I get 404

Please ask someone in your circle to re-check.

Thanks

On 8 June 2015 at 22:42, leggewie <notifications@github.com> wrote:

> works for me
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rgeissert/http-redirector/issues/60#issuecomment-110149697>
> .
>



-- 
Key fingerprint = EF78 310C C517 9564 9ECA  82F6 68FA E621 17E1 5D16
http://about.me/imranchaudhry

**Comment by 2vek** [comment]
for me `http://httpredir.debian.org/debian` results in a 404.
but `http://httpredir.debian.org/debian/` works fine. (notice the trailing slash in url)

Here is curl output

	$  curl -v http://httpredir.debian.org/debian
	* Hostname was NOT found in DNS cache
	*   Trying 5.153.231.35...
	*   Trying 2001:41c8:1000:21::21:35...
	* Connected to httpredir.debian.org (5.153.231.35) port 80 (#0)
	> GET /debian HTTP/1.1
	> User-Agent: curl/7.38.0
	> Host: httpredir.debian.org
	> Accept: */*
	> 
	< HTTP/1.1 404 Not Found
	< Date: Wed, 10 Jun 2015 04:18:05 GMT
	* Server Apache is not blacklisted
	< Server: Apache
	< Vary: Accept-Encoding
	< Content-Length: 274
	< Content-Type: text/html; charset=iso-8859-1
	< 
	<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
	<html><head>
	<title>404 Not Found</title>
	</head><body>
	<h1>Not Found</h1>
	<p>The requested URL /debian was not found on this server.</p>
	<hr>
	<address>Apache Server at httpredir.debian.org Port 80</address>
	</body></html>
	* Connection #0 to host httpredir.debian.org left intact


	$  curl -v http://httpredir.debian.org/debian/
	* Hostname was NOT found in DNS cache
	*   Trying 5.153.231.35...
	*   Trying 2001:41c8:1000:21::21:35...
	* Connected to httpredir.debian.org (5.153.231.35) port 80 (#0)
	> GET /debian/ HTTP/1.1
	> User-Agent: curl/7.38.0
	> Host: httpredir.debian.org
	> Accept: */*
	> 
	< HTTP/1.1 302 Found
	< Date: Wed, 10 Jun 2015 04:25:50 GMT
	< Location: http://mirror.isoc.org.il/pub/debian/
	< Content-Type: text/plain
	< X-Clacks-Overhead: GNU Terry Pratchett
	< Vary: Accept-Encoding
	< Transfer-Encoding: chunked
	< 
	* Connection #0 to host httpredir.debian.org left intact

**Comment by rgeissert** [comment]
Hi,

This is not a bug in the codebase itself, and there is even a note about it in the homepage that reads:
"Note: some people test the above URLs by copying&pasting them as-is in their browser. You need to add a slash at the end. E.g. /debian/. "
